packages:
  - 'android-docs'
  - "cs-guide"
  -  "git-tutor"
  -  "think-in-java"
  -  "node-docs"
  -  "wangdoc"
  -  "cg-tutor"
  -  "childhood"
  -  "baike"
  -  "flutter-docs"
  -  "CS-Notes"
  -  "hope-demo"
  - "cs-tips"
